// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKn97Vbs_VHPVtv0o_ejx4Efj5kPOsRJc',
    appId: '1:989890540978:web:e2fc910f67824ca1e260ab',
    messagingSenderId: '989890540978',
    projectId: 'sherpa-app-production',
    authDomain: 'sherpa-app-production.firebaseapp.com',
    storageBucket: 'sherpa-app-production.firebasestorage.app',
    measurementId: 'G-3LNW2TM87Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmHZE_rha3UnYHKQUf2EQussuq8qOeVEs',
    appId: '1:989890540978:android:b6c7bc5b96b9101ae260ab',
    messagingSenderId: '989890540978',
    projectId: 'sherpa-app-production',
    storageBucket: 'sherpa-app-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbbLU8632VLhrzLSpvE7GRsBrqrLliu34',
    appId: '1:989890540978:ios:8b9787f1c6dafc68e260ab',
    messagingSenderId: '989890540978',
    projectId: 'sherpa-app-production',
    storageBucket: 'sherpa-app-production.firebasestorage.app',
    iosClientId: '989890540978-j4kncp6fvcnmq62j82n6rji6790lbjvp.apps.googleusercontent.com',
    iosBundleId: 'com.sherpa.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbbLU8632VLhrzLSpvE7GRsBrqrLliu34',
    appId: '1:989890540978:ios:acce3b24ca35090ee260ab',
    messagingSenderId: '989890540978',
    projectId: 'sherpa-app-production',
    storageBucket: 'sherpa-app-production.firebasestorage.app',
    iosClientId: '989890540978-75qf04g2svl0k1ok2fu28cp615oa68ci.apps.googleusercontent.com',
    iosBundleId: 'com.example.sherpaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKn97Vbs_VHPVtv0o_ejx4Efj5kPOsRJc',
    appId: '1:989890540978:web:5f04a863ee50f088e260ab',
    messagingSenderId: '989890540978',
    projectId: 'sherpa-app-production',
    authDomain: 'sherpa-app-production.firebaseapp.com',
    storageBucket: 'sherpa-app-production.firebasestorage.app',
    measurementId: 'G-6TSG6E5B36',
  );
}
